controller_list:
  - name: fake_hexa_base_controller
    type: $(arg fake_execution_type)
    joints:
      - firefly_base
initial:  # Define initial robot poses per group
#  - group: hexa_base
#    pose: home

  []